### ISSUE TITLE
Phasmophobia widget v2 sizing

### ISSUE THREAD

**Issue by LadyZombie** [GlitchedMythos/se-widgets#12]
Changing font size doesn't change its appearance on stream!

**Comment by TheSquall** [comment]
Not sure if this is the case, but remember to hit the save button on the top right of StreamElements each time you make a change that you want to appear on the "Live Widget".

**Comment by LadyZombie** [comment]
This issue has been closed for some reason. However, the issue has not been solved. 
To demonstrate... A font size 41 should not be the same as a font size 14.


![1](https://user-images.githubusercontent.com/83652852/120088866-eb493800-c12f-11eb-809a-a7e01535dcb7.png)
![2](https://user-images.githubusercontent.com/83652852/120088867-ed12fb80-c12f-11eb-892e-d3d3c44371bd.png)
![3](https://user-images.githubusercontent.com/83652852/120088868-ee442880-c12f-11eb-8764-24bea20e2845.png)

**Comment by GlitchedMythos** [comment]
@LadyZombie I believe you may be on version 2.0.

Version 2.1 requires manually copying the code over from Github as shown in the YouTube video. StreamElements has not updated the one click install link.

**Comment by TheSquall** [comment]
Do some of these require using px vs. not px in the font size number instead of just the number? I never standardized them, and I don't know if you ever did either @GlitchedMythos?

**Comment by GlitchedMythos** [comment]
@TheSquall Ah! I had forgotten about that. I've been focusing on v3 (which has that all standardized), so it slipped my mind. That likely is the problem there. @LadyZombie try adding `px` after the number.

**Comment by LadyZombie** [comment]
Adding px with no space works! Thank you! 

And I'll double check which version I'm on! I've only been using it for the past month or so, so I assumed I was on the latest version!
