### ISSUE TITLE
V3 - Optional Strikethrough Alignment is too high

### ISSUE THREAD

**Issue by TheSquall** [GlitchedMythos/se-widgets#22]
[Strikethrough alignment is too high on V3 beta](https://cdn.discordapp.com/attachments/824665964212912128/849625238903193601/unknown.png)

**Comment by TheSquall** [comment]
This should be fixed by regressing #21, but I'm not sure what was seen that led to this PR, so I can't guarantee.

**Comment by GlitchedMythos** [comment]
Fixed by https://github.com/GlitchedMythos/se-widgets/commit/335a54b111f159f6cdace04cb6a81765c2b81eec
