### ISSUE TITLE
Suggestion: Add Dirty Water Tracker

### ISSUE THREAD

**Issue by stickybombz** [GlitchedMythos/se-widgets#30]
Much like the Bone and Oujia Board tracker that was put in, Would be nice to also have a tracker for if we found Dirty Water. This could be something that can be turned on or off like the others, and would be a Water Drop

**Comment by billyjbryant** [comment]
@GlitchedMythos I'll take this one, assign it to me :)

**Comment by GlitchedMythos** [comment]
Completely with PR #44
