### ISSUE TITLE
[Feature Request] Permit support for Subs and A subset of Followers to control widget

### ISSUE THREAD

**Issue by billyjbryant** [GlitchedMythos/se-widgets#40]
#### Description
I would like to have the ability to allow Subscribers who are not VIPs and maybe even Followers (Either All followers, or Followers who have followed for X amount of time/days [not sure if StreamElements can expose this]) to control the widget. 

This should be toggle controlled much in the same way that the VIP On/Off is.

**Comment by billyjbryant** [comment]
@GlitchedMythos I'm working on this change, you can assign this to me.

**Comment by GlitchedMythos** [comment]
Awesome. This'll be a good update and I'll make sure to clean this issue up after we merge in.
