### ISSUE TITLE
Request : Phasmophobia widget : add orbs as fourth evidence for the mimic

### ISSUE THREAD

**Issue by alyxal** [GlitchedMythos/se-widgets#57]
As there is always ghost orbs with a mimic.

I understand that is not an evidence accepted by the journal, but currently the widget set orbs as negative when you have spirit box + fingerprints.
It shouldn't be negative as it is a great evidence to determine if the ghost is a mimic (and as the mimic is officially an entity with four evidences)

I can totally do it - just wanted to have your opinion about it :)

**Comment by billyjbryant** [comment]
We had this originally, but it caused some confusion with the widget's usage and made for a very complicated mechanism of supporting the evidence.

**Comment by billyjbryant** [comment]
If you want to see how this can be implemented in your local copy of the widget you can reference https://github.com/GlitchedMythos/se-widgets/commit/a25080175d3ff59b12fc761cce54d1faa4d5342b
