### ISSUE TITLE
Command to Reset Evidence

### ISSUE THREAD

**Issue by drisanar-m** [GlitchedMythos/se-widgets#59]
Hi there, 
Is there a way to create a command that'll reset all evidence back to OFF at the end of a game? When I do it individually, it fills up my chat with the commands and is a little overwhelming. It would be very helpful if there was just 1 command I could enter that would clear the evidence. The way I'm doing it now I just 'edit' my overlay in Streamlabs and save it to reset everything on my Stream, which also clears out my counter. Which I don't want to clear out. 
Any ideas?

**Comment by GlitchedMythos** [comment]
In the README.md, there are directions on all the commands: https://github.com/GlitchedMythos/se-widgets/tree/main/phasmophobia_evidence_tracker

Also, in StreamElements, all the commands are editable in the side panel under the Commands panel. 

Generally for resetting !gr is used. You will need to confirm this in your overlay by looking for the Ghost Reset command. 

I’m closing this issue as it is part of the README and currently implemented.

**Comment by drisanar-m** [comment]
Thank you! I think I was confused because it was labeled as Name Reset for the !gr command. Thank  you again! Much appreciated. 

<html>
<body>


Name Reset | !gr | Reset the ghost
-- | -- | --
Name Reset | !gr "name" | Reset the ghost with the name


</body>
</html>
