### ISSUE TITLE
New Parabolic Microphone optional objective missing after Apocalypse (0.7.0.0) patch

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#63]
The new objective is "Detect a paranormal sound with a Parabolic Microphone"

Suggestion, after line 77 in widget.js:
```
mi: "Microphone",
mic: "Microphone",
microphone: "Microphone"
```
Note; I believe adding "Parabolic Microphone" would be too much text in the widget

**Comment by billyjbryant** [comment]
Adding this to #69

**Comment by GlitchedMythos** [comment]
Confirmed that I've seen this and actively looking for it in #69
