### ISSUE TITLE
Sunny Valley rename to Sunny Meadows

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#64]
After Apocalypse (0.7.0.0) patch, the new map Sunny Meadows (and Sunny Meadows Restricted) was introduced, this needs updating in the widget to replace Sunny Valley

Suggestion, update lines 107 and 108 in widget.js:
```
  su: "Sunny Meadows",
  sunny: "Sunny Meadows",
```

**Comment by billyjbryant** [comment]
This will be fixed in #69 which overhauls several areas of the script to improve performance.

**Comment by GlitchedMythos** [comment]
Same as the other issues, making sure it is in #69
