### ISSUE TITLE
!sight bone command not working

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#67]
The `!sight bone` command doesn't currently work for enabling or disabling the Bone icon

**Comment by AshKapow** [comment]
This is fixed by #66 BUT requires the widget to be re-created or by manually editing the "Bone (Comma Separated)" command in Stream Elements. The fix will not update it if already existing.

**Comment by billyjbryant** [comment]
@AshKapow the `!sight` and `!poss` commands utilize user defined trigger words which can be configured in `Settings > Commands`. There is no code fix required to resolve this issue.

**Comment by GlitchedMythos** [comment]
I believe that this is true, but I'll double check it in the next couple days as I update everything in the repo.

** Why was I absent for so long? See here: https://github.com/GlitchedMythos/se-widgets/issues/70

**Comment by GlitchedMythos** [comment]
After manual review. I think this is okay, even though it does break the normal flow for configuring the widget. Generally we have the different options be part of the codebase. Sight looks to be the only command that allows you to change the command variable options in that fashion, so it gets a bit confusing.

I think an improvement could be to separate those into a Command - Sights section.

**Comment by billyjbryant** [comment]
@GlitchedMythos it looks like the functionality of Sightings and Possessions changed with the merger of #54

**Comment by billyjbryant** [comment]
I think a good way to solve for this would be to move Possessions and Sightings back into their own array (like Optional Objectives) then allow a single word/phrase override (or add-in) from settings for those streamers who have a specific term they prefer for that Possession/Sighting. Would give the best of both worlds, uniform anticipated and regex-able words for the defaults and custom words for those who want them.

**Comment by GlitchedMythos** [comment]
This does sound good. I'm bogged down for at least a couple weeks dev-wise with work. Do you have capacity? @billyjbryant

**Comment by billyjbryant** [comment]
@GlitchedMythos Yes, I will take on this change :)

**Comment by GlitchedMythos** [comment]
@billyjbryant Appreciate you!

**Comment by GlitchedMythos** [comment]
Also, noticed that this is basically #19 , so I'm going to close that one

**Comment by AshKapow** [comment]
This has been resolved.
