### ISSUE TITLE
!sight slender not working

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#68]
The `!sight slender` (or similar) commands do not work and nothing happens when they are triggered

**Comment by billyjbryant** [comment]
@AshKapow can you share what is configured for your trigger words for the Sightings? 

These are configured in `Settings > Commands` . See the screenshot below: 

![image](https://user-images.githubusercontent.com/3013565/198817682-0600b062-44ab-4ea8-88c1-b43fa8b0845b.png)
