### ISSUE TITLE
Cannot select "Sunny Meadows" map - defaults to "Sunny Meadows (Restricted)"

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#71]
After the changes in the latest Apocolypse patch - we are now unable to select the "Sunny Meadows" maps, all other maps seem to work. If you choose "sunny" or "sunnymeadows" etc, it will show "Sunny Meadows (Restricted)" and not "Sunny Meadows". I'm guessing this is due to the new map lookup feature https://github.com/GlitchedMythos/se-widgets/blob/main/phasmophobia_evidence_tracker/widget.js#L1431

**Comment by GlitchedMythos** [comment]
Yeah. I believe you can get "Sunny Meadows (Restricted)" by typing "Res" or even more like "Rest", "Restr", "Restricted", etc.

I believe that requires a documentation update if that's the case. I have a chance later to go double check, but if @billyjbryant could confirm, that'd be awesome.

**Comment by AshKapow** [comment]
It doesn't matter which part of the map you type, it will always end with "Sunny Meadows (Restricted)" - you cannot select "Sunny Meadows" as "Sunny Meadows (Restricted)" takes precedence

**Comment by GlitchedMythos** [comment]
I now understand. I misunderstood and flipped the ask on that. Based on my knowledge of it working off regex, this would be correct.

I'll see if I can take a gander later and figure out a solution. This feels like an interesting little problem :D

**Comment by billyjbryant** [comment]
I could have sworn I tested this to work, I'll check it this evening

**Comment by billyjbryant** [comment]
@AshKapow can you pull #73 and see if this resolves your issue as expected?

**Comment by AshKapow** [comment]
@billyjbryant yep, this fixes the map issue

**Comment by billyjbryant** [comment]
Thanks for testing, @GlitchedMythos please merge when ready :)
