### ISSUE TITLE
Mods not able to update widget after Apocalypse patch (part two)

### ISSUE THREAD

**Issue by AshKapow** [GlitchedMythos/se-widgets#75]
Continuation from #72

I've been through with one of the streamers now with debugging enabled. They attempted with Mods, VIP and Trusted Users allowed. Still, for whoever tried to use the widget (not including the streamer), the user level came up as 'undefined' -- is it possible to be an issue with the widget picking up the user badges in some cases?

**Comment by billyjbryant** [comment]
@AshKapow can you provide the console logs from debugging?

**Comment by Hynaton** [comment]
Same
Only the streamer can use the commands

**Comment by AshKapow** [comment]
@billyjbryant I can try and get one of the streamers I work with to do this, as I personally cannot replicate this, but I know two streamers that have the same issue.

@Hynaton do you have the exact logs from the debug console?

**Comment by Hynaton** [comment]
{Event: {…}}
VM1064 about:srcdoc:4712 {permission: 2, data: {…}, arguments: Array(3), command: ƒ}
VM1064 about:srcdoc:4740 {userLevel: undefined, commandLevel: 2}

**Comment by AshKapow** [comment]
@Hynaton can I just ask... can you attempt to set up a second version of the widget, from scratch and see if that works? All my tests of creating it from scratch seem to work without any issue

**Comment by billyjbryant** [comment]
> {Event: {…}} 

@Hynaton 
Can you expand these out in your console then copy them or right click the messages and click "Save As" then upload the log to a new comment?

**Comment by billyjbryant** [comment]
@AshKapow would you be willing to test on my channel in offline chat? (You'd need a Twitch chat client like Chatty to interact)

**Comment by AshKapow** [comment]
@billyjbryant happily. Let me know when is best for you

**Comment by AshKapow** [comment]
I'm happy to start work on the updates for the new release, but I do really think this issue needs to be resolved as a priority (IMO) if anyone has time?

**Comment by billyjbryant** [comment]
New release is in #79 

I have had a lot of personal issues lately that have kept me from having time to devote to fixing the bug. I can try to set aside some time for this in the coming week if you would be available @AshKapow

**Comment by AshKapow** [comment]
@billyjbryant no worries! IRL always comes first!

**Comment by billyjbryant** [comment]
@AshKapow @jrowelltech @Hynaton could you please test with #79? I have recently pushed fixes for this bug in that PR.

**Comment by jrowelltech** [comment]
> @AshKapow @jrowelltech @Hynaton could you please test with #79? I have recently pushed fixes for this bug in that PR.

Tested last night, and works perfectly. I did realize that we never got a monkey's paw, so I didn't test that. I did explicitly test the permissions mod and VIP permissions, and they worked as expected.

**Comment by AshKapow** [comment]
All my testing seemed good. I will reach out to the streamers and ask them to test (but not sure when they will) but all looks good.
