### ISSUE TITLE
Request: Toggle individual "Impossible" Clues

### ISSUE THREAD

**Issue by TheSquall** [GlitchedMythos/se-widgets#9]
Request to have the ability to make certain clues impossible. For instance, if you know that the room the ghost is in is not freezing, you can remove that from possible choices to show what ghosts are available (especially helpful for 1 clue)

**Comment by billyjbryant** [comment]
This could be a right click option or a double toggle? IE Toggle On and off again to make it impossible?

**Comment by TheSquall** [comment]
Toggling it in the widget display is the easy part. It's the logic in the backend that I am not sure how to tackle -- Since you'd only have 5 clues (or however many based on what is impossible) instead of 6 available.

**Comment by GlitchedMythos** [comment]
This has been added in v3 as an option to give it a color. That can also be transparent.
